services:
  - type: web
    name: yukon-gold-casino-spinner
    env: static
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
