services:
  - type: web
    name: yukon-gold-casino-spinner
    env: static
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    # Performance optimizations
    plan: starter  # Use starter plan for better performance
    region: oregon  # Choose closest region to your users
